### ISSUE TITLE
CleverAdsSolutions-Base (~> 3.7.2)

### ISSUE THREAD

**Issue by bugrevealingbme** [cleveradssolutions/CAS-Flutter#11]
[!] CocoaPods could not find compatible versions for pod "CleverAdsSolutions-Base":
  In Podfile:
    CleverAdsSolutions-Base (~> 3.7.2)

    clever_ads_solutions (from `.symlinks/plugins/clever_ads_solutions/ios`) was resolved to 0.0.1, which depends on
      CleverAdsSolutions-Base (~> 3.6.0)

Specs satisfying the `CleverAdsSolutions-Base (~> 3.7.2), CleverAdsSolutions-Base (~> 3.6.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by piannelli** [comment]
Hi, the issue here is not about the target platform, but rather in file `clever_ads_solutions.podspec` which indicates as dependency:

```
s.dependency 'CleverAdsSolutions-Base', '~> 3.6.0'
```

For this reason CAS versions 3.7 and above are not compatible. Please fix the podspec :)

As a workaround users can edit the file in `ios` directory:

`.symlinks/plugins/clever_ads_solutions/ios_clever_ads_solutions.podspec`

and change CleverAdsSolutions-Base dependency to `> 3.6.0`

**Comment by piannelli** [comment]
Well, nevermind, I guess CAS Flutter 0.3.0 doesn't support CAS-iOS 3.7, since it will fail at CASTargetingOptions not having Gender member. We will wait for next CAS flutter version, so we can integrate new SDK versions! :)
